### ISSUE TITLE
Priority 

### ISSUE THREAD

**Issue by idfktbh** [safing/portmaster-ui#125]
You should add a feature so you can set app priorities. 
so you getter better ping in games

**Comment by dhaavi** [comment]
Hey @idfktbh, thanks for the feature request.

Prioritizing connections within the Portmaster is not possible, as the connections themselves are handled by the Operating System, ie. Windows or Linux. The Portmaster only blocks unwanted connections, but is not in charge of the network stack, and thus is unable to change behavior of that aspect.

However, it is possible to do this when using the [SPN](https://safing.io/spn/). I created a feature request in the corresponding repo: https://github.com/safing/spn/issues/10

Please feel free to elaborate on your suggestion there. I will close this issue here, as it is not applicable.
