### ISSUE TITLE
Temporary allow actions for prompts

### ISSUE THREAD

**Issue by robjob1938** [safing/portmaster-ui#151]
**What would you like to add or change?**:
instead of a blanket Allow, it would be really nice to have "Allow for 5 minutes" or "Allow until restart"

**Why do you and others need this?**:
For example, I may want to run linux updates, but only allow that app to run for a limited time to download the updates.  Also, I don't want youtube.com to have access unless I go to youtube to watch something specific for 10 minutes.

**Comment by dhaavi** [comment]
Hey @robjob1938,

that's a great suggestion. Technically such a feature would not pose a challenge, but what makes this difficult is how to communicate temporary settings to the user and what to bind them to.

Would they be displayed somewhere in the app settings? Or in the network monitor? What happens when the user adds a contradicting permanent rule while the temporary one is still active?

I do like the idea of allowing something until restart. The question is which restart? Of the OS? Of the Portmaster? Of the program itself?

To take your example: Linux updates.
Did you know that, for example, apt uses a helper bin at `/usr/lib/apt/methods/http` to make network requests? It uses multiple instances, so if we bind the temporary rules to the PID, you'll have multiple prompts to take care of just for running `apt update`.

As you can see, all of this isn't that simple after all. But I definitely see the value, and I think working through all these questions and finding a good solution is definitely worth the effort. I cannot, however, say when we'll find the time to do so.

I will talk with the team about possible options. If you have any suggestions, please share them!
Internal note: tracked by CC#1955.

**Comment by robjob1938** [comment]
Before I started using portmaster, I used opensnitch.  Opensnitch allowed for timers, maybe you can see their code https://github.com/evilsocket/opensnitch @dhaavi

**Comment by supracoralline** [comment]
> I do like the idea of allowing something until restart. The question is which restart? Of the OS? Of the Portmaster? Of the program itself?

I think it's better to clear it once the OS **and/or** Portmaster restarts; this way, users don't have to re-configure the temporary settings in case the app crashes or is restarted. 

You can also give the user an option to clear all temporary allowed connections (like a panic button).
