### ISSUE TITLE
Concept UI for Portmaster

### ISSUE THREAD

**Issue by additionalpoints** [safing/portmaster-ui#175]
![Settings Page](https://user-images.githubusercontent.com/89087265/138166622-32bbb529-4c25-4a44-9c44-6368cd46fd02.png)

I feel a navbar solution and a cleaner UI is more natural since that's what we're accustomed to with most operating systems. The first icon is an analytics tab which shows graphs of the network connections which I feel is a sorely missing feature. Second one is the overview tab, third is network rating, and finally settings.

This is just a simple prototype so I didn't bother to add the tip icons which are a helpful addition in the current UI.

**Comment by thegranddesign** [comment]
Just leaving my 2 cents here as I feel like the current Portmaster UI is trying to do way too much for the most common use cases.  I really think the Little Snitch UI hits it out of the park here.

**Comment by LukeSeers** [comment]
> I really think the Little Snitch UI hits it out of the park here. 

I have to agree with your point. The current UI/UX of the Portmaster is definitely lacking in that area compared to Little Snitch. This version of the UI/UX is more or less slapped together to just get an idea of what information/data we have and we plan on re-evaluating on how to display that type of information/data.

> We should be careful with being different or "more advanced" just for the sake of it.

I yet again agree. Two of these cases of it being pretty advanced/spooky

1.  **The settings**: Users don't really understand on how to enable/disable a setting within the global/app settings when using the multi-toggle switch. The multi-toggle switch was created due to how the Portmaster was implemented, but it was flawed from the start in regards to UX and we tried to kind of deal with it, but it wasn't good enough.
2. **Data/Information**: There is a excessive amount of data/information in the Portmaster that the normal user wont really use.


The cool thing is that we are working on re-evaluating the UI/UX now as we speak. Here's a couple of things you may like the sound of :) 

1.  **The settings**: As I mentioned before the settings has a huge flaw, people don't know how to enable/disable a setting and that's horrible. In the new version this is changing, now it will be just a simple **on/off** toggle for each setting.
2.  **Apps Page**: Before this was just settings, and how it was displayed was also pretty confusing too. But, now it's having a facelift. I hope with this new facelift we'll start to head in the direction of Little Snitch in regards to UX. We still have along way to go, but I feel it's the right step in that direction.

I don't know when these big changes will be coming out, but it will be interesting to get your feedback when it does. Ofc, this is fully up to you if you wish to give us more feedback, but we will be very grateful if you do :)

**Comment by Raiyan-AP** [comment]
@davegson I think the Network Monitor is good enough. Just needs to be a bit more concise with how things are laid out. More icons and visuals could help understand things at a glance and the important and most used parts could be emphasized so users can interact with it easier. There's also a lot of unused space in the middle that could be used give the UI more room to breath.

Right now I'm a bit busy so when I have the time I'll post a concept a here. And I did not mind at all doing this since it was fun little activity to do and helped in polishing my UI skills.

**Comment by gedw99** [comment]
i am new here, and really like what this project is doing.

I have been using GIOUI. The reason i bring it up is because it allows you to build UI for web, Desktop and Mobile using only golang. 

I am been usig it to build Medical systems that can run anywhere. Its refreshing to not have to build for web / webview just because  its the only portable game in town.

https://github.com/gioui

There are a few golanger developer using it.

try this one to get your feet wet: https://github.com/gioui/gio-example/tree/main/component
