### ISSUE TITLE
[Question] Why Google Chrome and Golang

### ISSUE THREAD

**Issue by philippklemmer** [safing/portmaster-ui#22]
So i've looked shortly over your code and what i discovered was, that you are using Google Language and it's browser and the Go wrapper to have an Desktop App. How can you verify, that Google is not tracking any data? Why don't you use like firefox and build a wrapper for it or build the ui in a native wrapper (this will take far longer, than the approach you're following right  now, i know :D)? 

If  this doesn't belongs in here, feel free to tell me where i can post this question :) Found you through @thehatedone and love your idea!

**Comment by davegson** [comment]
Hey @philippklemmer, thank you for your great questions!

**A short disclaimer:** @dhaavi, our main dev for Portmaster & Gate17 and the one who can get to you in more detail, will probably only be able to come back to you in September.

Until then, I hope my thoughts will help a bit. [Golang](https://golang.org/) is an open source project - everyone can check whether it sends data to google or not. And from what I know, this is not the case.

Why I think you might assume this are stories from developers using iE the Facebook SDK to build an Android App, which provides features such as built in Analytics, which of course: sends data to Facebook. Which is kinda the point why Facebook develops the SDK.

A programming language is different, since there is no built in communication with the parent company. Here the benefit for the company is just technical. Another example of a big tech corp developing a programming language is [Facebook's react](https://reactjs.org/) - which helps them for better front-end processing. And also helps their reputation among developers.

But yeah, that's my quick two cents. Looking forward to hear Daniels thoughts.

And what did you mean by we use Google Chrome? That is not accurate as far as I know.

PS: wooo, @TheHatedOne - he's a great guy :), happy to hear you found us through him!

**Comment by philippklemmer** [comment]
@davegson thanks for the fast reply! 
I think that you already have answered everything for me. I can not remember where i found something about a desktop gui wrapper of googles chrome, but nvm. I looked again at your code and I love that you are building a desktop app without electron!! How can I support you guys?

**Comment by davegson** [comment]
@philippklemmer no worries - very glad to hear you like it!!

Support in what way? Depending on what you mean I'd link you to a different channel. You can also [hit me up on Twitter @davegson](https://twitter.com/davegson), PMs open ;)

**Comment by dhaavi** [comment]
Hey @philippklemmer, thanks for the great question! Sorry for chiming in so late.

If you have any further questions, please check out our community on [r/safing](https://www.reddit.com/r/safing/) and post your question there for greater visibility!
