### ISSUE TITLE
Permanent history

### ISSUE THREAD

**Issue by Frostedfox** [safing/portmaster-ui#226]
**What would you like to add or change?**:
I would like to have a permatent history of all the connections made, not just 10 minutes. but atleast upto a month

**Why do you and others need this?**:
This would help everyone to analyze their traffic patterns and make informed desicions

**Comment by itsnotsaved** [comment]
Add option to select retention period: 10 minutes, 1hr, 6hr, 1 day, 7 days, 1 month, 6 months, 1 year, forever.
I was searching glasswire alternative to linux but never found, it store history since installation then portmaster is linux glasswire https://www.glasswire.com/

![image](https://user-images.githubusercontent.com/73447325/164381753-94ccbe69-686e-4ee7-aa33-a5e8a1a409d2.png)

**Comment by dhaavi** [comment]
This is on the way, but will still take some more time.

We are currently rebuilding the whole network monitor page to be much more powerful. That will lay the groundwork for a permanent history.

**Comment by davegson** [comment]
just as a reference: https://github.com/safing/portmaster/issues/682

**Comment by OfficialEsco** [comment]
Network History was added in Portmaster 1.3 https://safing.io/blog/2023/08/08/portmaster-v1.3/
