### ISSUE TITLE
UI Zoom/Scaling control for font & icons (Or General UI)

### ISSUE THREAD

**Issue by Aravinth-Earth** [safing/portmaster-ui#233]
**What would you like to add or change?**:
I would like to have an option to adjust the scale of how text, icons being displayed. There should be an option to adjust the scale in percentage as in variants of 10 [ Like, 50%, 60%, 70%, 80%, 90%, 100%{being the default}, 110%, 120%, 130%, 140%, 150% ]

**Why do you and others need this?**:
As my display is larger comparative to most display resolutions size in consumer market(As i believe). The text (in almost all sections) is not at all readable!!!. Hence this additional control will help user of large & small screen machines.
![In-App different font size in Settings](https://user-images.githubusercontent.com/55803552/166896757-eccbe053-7c02-4b55-9ca5-05f3b732b850.png)
![Safing small Fonts](https://user-images.githubusercontent.com/55803552/166896768-f86488cb-506b-4748-8894-a3278b763540.png)

**Comment by p2anav** [comment]
The UI is based on electron and I expect zoom in/out to work like a browser using _Ctrl_ + _Scroll_ or _Ctrl_ + _+_ for zoom in, _Ctrl_ + _-_ for zoom out, _Ctrl_ + _0_ for zoom reset, but for some reason the Portmaster UI is accepting _Ctrl_ + _Shift_ + _+_ for zoom in instead of _Ctrl_ + _+_. Others keys work fine.

**Comment by Aravinth-Earth** [comment]
I tried all possible combinations  { Mouse, Track-pad gesture, Keypad & Keyboard } & unfortunately nothing helps!
For testing, when i go to 'Web Developer Tool' section of Portmaster UI, there the Ctrl+ + & Ctrl + - works, But not in the main window, Any more suggestions ?

**Comment by p2anav** [comment]
As far as I understand there should also be an option in the UI for zoom controls. @dhaavi?

**Comment by Aravinth-Earth** [comment]
@dhaavi @p2anav - Any other suggestions or troubleshooting options to tryout?

**Comment by LukeSeers** [comment]
@Aravinth-Earth What your looking for mate is `F11`. In the Portmaster UI press `F11` go to `View > Zoom In/Out`. 

This also should be saved too, so when you open it the next time it will be the zoom amount you have set.

![Screenshot 2022-06-01 at 14 13 26](https://user-images.githubusercontent.com/16389426/171401792-a1273831-8eda-4a30-8d22-ce691d65d1c9.png)

**Comment by Aravinth-Earth** [comment]
@LukeSeers This is the exact control/setting i was looking for, Thank you :)

As this helps in my case(and hopefully other in UI/Scaling issue), It is good to close this issue. Unless @dhaavi  @p2anav  want to keep it as open for any other development reasons

**Comment by LukeSeers** [comment]
Sorry @p2anav I'm going to reopen this ticket, due to the fact my solution was a hacky fix and not a solid solution.

I've also gone ahead and added this into our internal CC #2377 to more easily keep track of this suggested feature.

**Comment by p2anav** [comment]
Yeah, no problem.

**Comment by Digital-ecologist** [comment]
@p2anav Thanks for bringing this thread to my attention.  :-) 
Sorry I missed it as I was scrolling through the issues. Excited to more actively be able to use the tool set on Windows, now that I've got the scaling right!

**Comment by 0ecd3e** [comment]
Is this located on the FAQ or Help sections anywhere? I couldn't find it. F10 to open a hidden menu bar is a leap for many users, I only happened to find this thread because I wanted to make the same feature suggestion. There should be some type of menu option accessible from the regular interface, or at least a note in the software itself suggesting the use of F10. Posting a tip in the Portmaster Tour is probably the fastest way to do it.

**Comment by Digital-ecologist** [comment]
Hi, I think the F10 thing is specific to certain Linux desktops, on Windows it's just [ctrl +] & (ctrl -] although weirdly, I have to use the plus and minus in my number row. It doesn't work if I use the ones in the number pad. I think that's why I didn't find it myself the first time, I tried the key combo, but on the number pad. All for this being more obviously documented/visible somewhere.

**Comment by 0ecd3e** [comment]
@Digital-ecologist I'm running Windows, Ctrl + "-" works to zoom out but Ctrl + Shift + "+" is needed to zoom in (not number pad). F10 worked for me, and seems to be Electron app dependent (doesn't work in Slack, for example). Can't speak for the number pad myself, but I have a feeling the key combo is looking for the "+" character from the regular keyboard which is different from the "+" character sent from the numpad (same goes for the "-").

**Comment by Digital-ecologist** [comment]
Thanks for chiming in,  just poked at the keyboard some more, and mine is [Fn + F10]. Thanks for confirming that it worked in Windows. Nice to have a menubar now.  Guess it's a case of keyboard variability.

**Comment by yellowgh0st** [comment]
I highly suggest to add also way to adjust scaling into app global settings for user convenience.
