### ISSUE TITLE
In App Page, "Connection Setting Detail" should use Full Space

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#291]
![image](https://user-images.githubusercontent.com/62152714/184479749-87961269-c514-4cc1-b74f-d19ff3319894.png)
![image](https://user-images.githubusercontent.com/62152714/184479814-3736493a-6feb-40ad-a56c-635f5f6a188b.png)

**Comment by Rexadev** [comment]
@p2anav "Connections Settings Details" tabs should use all the space available

**Comment by dhaavi** [comment]
Pinging @LukeSeers for this.

**Comment by LukeSeers** [comment]
Thank you for the suggestion, but sadly there is no reason to change this. Not to mention having it full width can cause problems down the lines when we add more tabs, since it would change the position of the tabs.

I will close this ticket, but if you think there is a solid reason on why we should do this please reopen this ticket.
