### ISSUE TITLE
Name Exe depending on folder

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#309]
Like Firefox folder has crash reporter is should be called Firefox - Crashreporter
![image](https://user-images.githubusercontent.com/62152714/186499596-f3aa3526-c8ac-4c1a-b6c1-7059383a6dae.png)

**Comment by ppacher** [comment]
This is an interesting idea but I fear it will not solve the underlying issue here and will also not work on other operating systems since on linux, for example, most binary paths are stored under `/usr/bin` and prefixing all of them with `usr` doesn't seem like a reasonable solution to me.

This issue is better addressed with wildcard/regex path matching of profiles since that would be capable of grouping binaries from the same application together - still, while this is already planned it will required some time until we find the resources for that.

Closing this here for now, feel free to re-open if you don't agree :)

**Comment by Rexadev** [comment]
@ppacher please mark this as "waiting for resources" instead and rename title
