### ISSUE TITLE
Don't show loopback in Country N/A

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#312]
![image](https://user-images.githubusercontent.com/62152714/186852357-f2f8b3a9-b91f-4e47-8fca-3e51046b0749.png)

**Comment by ppacher** [comment]
Hi @Rexadev,

thanks for the suggestion but I believe this is the correct behavior. If I'm searching for connections that are not attributed to a country I would expect to get all LAN and loopback connections since they are naturally not "country attributable".

I'm closing this here but feel free to continue the discussion.

**Comment by Rexadev** [comment]
@ppacher rename N/A to LAN/Device Local. N/A sounds like IP is not in database
