### ISSUE TITLE
Connections and App list overflow Options

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#317]
![image](https://user-images.githubusercontent.com/62152714/188378468-956dbfc1-c4f7-41bd-8e62-cd37f18e5a05.png)

![image](https://user-images.githubusercontent.com/62152714/188379612-2ab35cf5-e029-4aab-b606-d4792eb7311e.png)

1. Move App setting to App's overflow option
2. Move Global settings to one option per whole connection page
3. App option to block globally

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/190923915-003baeb2-c1e9-4ab6-a045-ace20a4be163.png)
![image](https://user-images.githubusercontent.com/62152714/190923942-d448b0de-35e0-4aa8-82bc-63974bc2562f.png)

**Comment by ppacher** [comment]
That difference is on purpose. You cannot "block the domain" for P2P connections since there's just not domain associated with it. 
`Allow Domain` is greyed out because you changed a setting on that app profile that cannot be overwritten by adding an "allow rule". See [here](https://github.com/safing/portmaster-ui/blob/develop/modules/portmaster/src/app/shared/netquery/pipes/can-use-rules.pipe.ts)

**Comment by Rexadev** [comment]
No app Settings and Global Settings options

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
For this reason this issue had to be closed.
