### ISSUE TITLE
Rename Global Rules to Default Rules

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster-ui#331]
If LAN is blocked in "Global Rules" but allowed for the app LAN connection is allowed

In Global RUles some are global like DNS some are default like LAN

**Comment by ppacher** [comment]
Can you please elaborate. There do you see that?

**Comment by davegson** [comment]
thanks for your input!

> If LAN is blocked in "Global Rules" but allowed for the app LAN connection is allowed

I don't understand your confusion, since when you click on the (i) next to Global settings it says:

> Here you can set system-wide preferences and configure default rules for all your apps and connections.
> It is easy to create a stricter global ruleset and then create exceptions in the app settings, which override the global default.

I do not think changing it to "Default Settings/Rules" will be a step forward. It might make one aspect of settings clearer, but make another aspect more confusing.

If you disagree or have a specific argument please let me know and I'll consider re-opening.

**Comment by Rexadev** [comment]
Split into 2 categories to avoid confusion
@davegson

**Comment by davegson** [comment]
then you have to move two related settings to different categories / tabs. Like the [DNS Exit Node Rules](https://docs.safing.io/portmaster/settings#spn/dnsExitPolicy) and [Exit Node Rules](https://docs.safing.io/portmaster/settings#spn/exitHubPolicy), which are _very_ related settings, but would suddenly be split apart - adding confusion for these scenarios.

I do not think there is the ideal solution covering all use-cases, somewhere we have to make drawbacks and accept confusion. And a simple (i) gives additional info to hopefully reduce confusion

**Comment by Rexadev** [comment]
@davegson 
Call it Settings and mention Global or Default for each sub section
