### ISSUE TITLE
Unable to change settings/ disable p2p

### ISSUE THREAD

**Issue by blindside1** [safing/portmaster-ui#61]
**Checklist**:

- [ x] I'm using the official portmaster release (i.e no custom builds)
- [ ] I searched for similar/existing issues first.
- [ ] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**: Unable to alter any of the settings in the ui. Also unable to start my VPN...

**What you expected to happen**: I have waited a week to see if the settings would be able to be changed by me. I even clicked on the "expert" box instead of "auto-pilot" to no avail. The vpn cannot even spin up now. 

**How to reproduce it (as minimally and precisely as possible)**: See above

**Anything else we need to know?**: No

**Environment**: Win10 EDU

Portmaster Version: 

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x
<img width="362" alt="AirVPN startup" src="https://user-images.githubusercontent.com/48873350/81088766-fa3cc700-8eea-11ea-989c-80f255649611.png">
<img width="495" alt="Portmaster settings" src="https://user-images.githubusercontent.com/48873350/81088770-fb6df400-8eea-11ea-8409-7c8f5a5bce62.png">

 ] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Portmaster\ļogs`

**Comment by ppacher** [comment]
Hi @blindside1 ,
thanks for getting back to us!

From what I can see on the screenshots you don't even see the edit buttons for the configuration settings. This seems to be related to #60 as the UI just doesn't scale on that screen size. Since this makes portmaster somehow unusable we'll try to push a fix for that as soon as possible. 

As a work around you can try changing the setting while the portmaster app is bigger than your screen (see #60). Change the `Block Peer to Peer Connections` to the "High and Extreme" (like the `Block Inbound Connections`). And select "Normal" mode on the dashboard. 

![screenshot](https://user-images.githubusercontent.com/1043756/81106405-d0e56080-8f15-11ea-97c5-efc7244e7e34.png)

**Comment by blindside1** [comment]
Thanks @ppacher for the response. I will keep working on it. If you want, I have another machine that is an ubuntu spinoff, PopOS, and start testing on that.
